ALTER TABLE ru_users ADD COLUMN `hash` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE ru_users ADD COLUMN `contact_name` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE ru_users ADD COLUMN `contact_phone` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE ru_users ADD COLUMN `contact_email` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE ru_users ADD COLUMN `people_no` INT(11) NULL DEFAULT NULL;
ALTER TABLE ru_users ADD COLUMN `flat_size` INT(11) NULL DEFAULT NULL;
ALTER TABLE ru_users ADD COLUMN `flat_no` INT(11) NULL DEFAULT NULL;
